format = """$character"""

right_format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$rust"""

[hostname]
ssh_symbol = "@"
ssh_only = false
trim_at = ""
style = "#9A348E"
format = "[$ssh_symbol$hostname]($style):"

[username]
style_user = "bold #9A348E"
style_root = "bold #9A348E"
format = "[$user]($style)"

[directory]
style = "#DA627D"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "#FCA17D"

[git_status]
format = "[$conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed]($style)"
style = "#FCA17D"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#FCA17D"

[cmd_duration]
format = " [$duration]($style)"
style = "#33658A"

#[python]
#format = "[$virtualenv]($style) "
#style = "bright-black"

[rust]
format = " [$toolchain]($style) "
style = "#86BBD8"
